### ISSUE TITLE
友情链接 | IFreeSync

### ISSUE THREAD

**Issue by ifreesync** [ifreesync/ifreesync-comment#2]
https://www.ifreesync.com/links/? 

 .links-content{          margin-top:1rem;          }          .link-navigation::after {          content: " ";          display: block;          clear: both;          }          .

**Comment by flowerunbeaten** [comment]
- 本站名称：IFreeSync
- 本站链接：https://www.ifreesync.com
- 本站描述：Light from the darkness,Darkness emergent light
- 本站图标：https://www.ifreesync.com/images/avatar/avatar.png
